# Generated by Django 6.0.4 on 2026-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
    ]
