# Generated by Django 6.0.4 on 2026-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_balance_paid_order_deposit_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_platform',
            field=models.CharField(choices=[('taobao', 'Taobao'), ('1688', '1688'), ('alibaba', 'Alibaba'), ('wechat', 'WeChat Supplier'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_note',
            field=models.TextField(blank=True),
        ),
    ]
