# Generated by Django 6.0.4 on 2026-05-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_source_link_product_source_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150)),
                ('supplier_contact', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_platform', models.CharField(choices=[('taobao', 'Taobao'), ('1688', '1688'), ('alibaba', 'Alibaba'), ('wechat', 'WeChat Supplier'), ('other', 'Other')], default='other', max_length=20)),
                ('source_link', models.URLField(blank=True)),
                ('rmb_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplier_requests/')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
