# Generated by Django 6.0.4 on 2026-05-03 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_supplierproductrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='supplier_requests/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('supplier_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.supplierproductrequest')),
            ],
        ),
    ]
