# Generated by Django 6.0.4 on 2026-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_supplierproductrequestimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="exchangerate",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="supplierproductrequest",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="delivery_range",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="exchange_rate_used",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="markup_used",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_max_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_min_days",
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=230, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="balance_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="deposit_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_arrival_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_arrival_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
