# Generated by Django 6.0.4 on 2026-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_order_balance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_proof_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
