# Generated by Django 6.0.4 on 2026-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_order_payment_proof_order_payment_proof_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproductrequest",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("preorder", "Pre-order from China"),
                    ("local", "Available in Zambia"),
                ],
                default="preorder",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
