# Generated by Django 6.0.4 on 2026-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_supplierproductrequest_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproductrequest",
            name="local_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplierproductrequest",
            name="rmb_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
