# Generated by Django 6.0.4 on 2026-05-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_supplierproductrequest_local_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproductrequest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
    ]
