# Generated by Django 6.0.4 on 2026-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_supplierproductrequest_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser_name", models.CharField(max_length=150)),
                ("headline", models.CharField(max_length=100)),
                ("subtext", models.CharField(blank=True, max_length=160)),
                ("image", models.ImageField(blank=True, null=True, upload_to="ads/")),
                ("cta_text", models.CharField(default="Visit", max_length=30)),
                ("cta_url", models.URLField()),
                (
                    "hour_slot",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "00:00 – 00:59"),
                            (1, "01:00 – 01:59"),
                            (2, "02:00 – 02:59"),
                            (3, "03:00 – 03:59"),
                            (4, "04:00 – 04:59"),
                            (5, "05:00 – 05:59"),
                            (6, "06:00 – 06:59"),
                            (7, "07:00 – 07:59"),
                            (8, "08:00 – 08:59"),
                            (9, "09:00 – 09:59"),
                            (10, "10:00 – 10:59"),
                            (11, "11:00 – 11:59"),
                            (12, "12:00 – 12:59"),
                            (13, "13:00 – 13:59"),
                            (14, "14:00 – 14:59"),
                            (15, "15:00 – 15:59"),
                            (16, "16:00 – 16:59"),
                            (17, "17:00 – 17:59"),
                            (18, "18:00 – 18:59"),
                            (19, "19:00 – 19:59"),
                            (20, "20:00 – 20:59"),
                            (21, "21:00 – 21:59"),
                            (22, "22:00 – 22:59"),
                            (23, "23:00 – 23:59"),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["hour_slot"],
            },
        ),
    ]
