# Generated by Django 6.0.6 on 2026-06-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_update_deposit_percentage_to_35'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_link', models.URLField()),
                ('source_platform', models.CharField(choices=[('alibaba', 'Alibaba'), ('taobao', 'Taobao'), ('temu', 'Temu'), ('1688', '1688'), ('shein', 'Shein'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='customer_product_requests/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('ordered', 'Ordered'), ('unavailable', 'Unavailable'), ('closed', 'Closed')], default='new', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_custom_status_821e1a_idx'), models.Index(fields=['created_at'], name='core_custom_created_1e07b9_idx')],
            },
        ),
    ]
