# Generated by Django 6.0.6 on 2026-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customerproductrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductrequest',
            name='customer_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerproductrequest',
            name='customer_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproductrequest',
            name='estimated_delivery_days',
            field=models.CharField(blank=True, default='14-30 days', max_length=40),
        ),
        migrations.AddField(
            model_name='customerproductrequest',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproductrequest',
            name='quoted_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
