# Generated by Django 6.0.6 on 2026-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customerproductrequest_customer_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductrequest',
            name='source_platform',
            field=models.CharField(choices=[('aliexpress', 'AliExpress'), ('alibaba', 'Alibaba'), ('taobao', 'Taobao'), ('temu', 'Temu'), ('1688', '1688'), ('shein', 'Shein'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_platform',
            field=models.CharField(choices=[('aliexpress', 'AliExpress'), ('taobao', 'Taobao'), ('1688', '1688'), ('alibaba', 'Alibaba'), ('wechat', 'WeChat Supplier'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierproductrequest',
            name='source_platform',
            field=models.CharField(choices=[('aliexpress', 'AliExpress'), ('taobao', 'Taobao'), ('1688', '1688'), ('alibaba', 'Alibaba'), ('wechat', 'WeChat Supplier'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
