# Generated by Django 6.0.6 on 2026-08-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_external_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional supplier availability for pre-order products.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.CharField(blank=True, help_text='Comma-separated colors, for example: Black, White, Blue.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='external_gallery_urls',
            field=models.TextField(blank=True, help_text='One external product image URL per line.'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.CharField(blank=True, help_text='Comma-separated sizes, for example: S, M, L, XL or 50 inch, 55 inch.', max_length=255),
        ),
    ]
