# Generated by Django 6.0.6 on 2026-08-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_available_quantity_product_color_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproductrequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_products', 'Can submit products as an approved supplier')]},
        ),
    ]
