# Generated by Django 6.0.6 on 2026-08-09 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_supplierproductrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The approved supplier account that submitted this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
