# Generated by Django 6.0.6 on 2026-08-20 06:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_create_cache_table"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="requested_color",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="requested_size",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="availability_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="availability_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="availability_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("awaiting_deposit", "Awaiting deposit"),
                    ("checking", "Checking with supplier"),
                    ("options_sent", "Available options sent to customer"),
                    ("accepted", "Customer accepted"),
                    ("cancelled", "Customer cancelled"),
                ],
                default="not_required",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("due", "Full deposit refund due"),
                    ("completed", "Full deposit refunded"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="availability_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="availability_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("pending", "Pending verification"),
                    ("available", "Available"),
                    ("alternative", "Alternative offered"),
                    ("unavailable", "Unavailable"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="available_colors",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="available_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="available_sizes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="requested_color",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="requested_size",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="imported_from_link",
            field=models.BooleanField(
                default=False, help_text="Imported from an external marketplace link."
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "requested_size", "requested_color"),
                name="unique_cart_product_variant",
            ),
        ),
    ]
