# Generated by Django 6.0.6 on 2026-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproductrequest",
            name="external_gallery_urls",
            field=models.TextField(
                blank=True, help_text="Imported image URLs, one per line."
            ),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="external_image_url",
            field=models.URLField(blank=True),
        ),
    ]
