# Generated by Django 6.0.6 on 2026-08-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_supplierproductrequest_external_gallery_urls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="displayed_price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="displayed_price_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="original_displayed_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_product_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="source_currency",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="product",
            name="source_product_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="variant_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="displayed_price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="displayed_price_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("partial", "Partial import"),
                    ("complete", "Complete import"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="imported_image_paths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="imported_store_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="imported_variant_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="original_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="original_displayed_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="original_product_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="price_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="selected_color",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="selected_other_variants",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="selected_size",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="source_currency",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="supplierproductrequest",
            name="source_product_id",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
