# Generated by Django 6.0.6 on 2026-08-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_product_displayed_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductrequest',
            name='estimated_delivery_days',
            field=models.CharField(blank=True, default='24-60 days', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_max_days',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_min_days',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
