# Generated by Django 6.0.6 on 2026-08-22 06:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_update_default_delivery_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'collection centre',
                'verbose_name_plural': 'collection centres',
                'ordering': ['town', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='collection_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Delivery fee (% of order subtotal) when the customer collects from a centre.', max_digits=5),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='direct_delivery_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Delivery fee (% of order subtotal) when the order is delivered directly to the customer's address.", max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee_percentage_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('collection', 'Collect from a Centre'), ('direct', 'Direct to Address')], default='collection', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.collectioncentre'),
        ),
    ]
