# Generated by Django 6.0.6 on 2026-08-22 09:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_collectioncentre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='biker_fee_share_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Share of the delivery fee (%) paid out to the biker who completes a direct delivery.', max_digits=5),
        ),
        migrations.CreateModel(
            name='Biker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Motorbike'), ('bicycle', 'Bicycle')], max_length=20)),
                ('id_number', models.CharField(blank=True, help_text="National ID or driver's licence number, for vetting.", max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Bikers can be paused without losing their history.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('home_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikers', to='core.collectioncentre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('biker_fee_percentage_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biker_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('biker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.biker')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_jobs', to='core.collectioncentre')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_job', to='core.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('checkpoint_type', models.CharField(choices=[('placed', 'Order Placed'), ('confirmed', 'Confirmed'), ('purchased', 'Purchased in China'), ('departed_origin', 'Departed China'), ('arrived_origin_port', 'Arrived at Origin Port'), ('in_transit', 'In Transit (Sea/Air Freight)'), ('arrived_zambia_port', 'Arrived in Zambia'), ('arrived_hub', 'Arrived at Regional Hub'), ('en_route_destination', 'En Route to Destination Town'), ('arrived_centre', 'Arrived at Collection Centre'), ('biker_assigned', 'Delivery Biker Assigned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('ready_for_collection', 'Ready for Collection'), ('collected', 'Collected by Customer'), ('delayed', 'Delayed'), ('other', 'Other')], max_length=30)),
                ('location_note', models.CharField(blank=True, help_text='e.g. "Choma Market Centre"', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Optional note shown to the customer.')),
                ('notify_customer', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='core.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
