# Generated by Django 6.0.6 on 2026-09-01 19:17

import django.db.models.deletion
from django.db import migrations, models


def create_default_variants(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    ProductVariant = apps.get_model('core', 'ProductVariant')
    variants = []
    for product in Product.objects.all().iterator():
        variants.append(ProductVariant(
            product_id=product.pk,
            sku=f"{product.sku}-DEFAULT",
            cost_price=product.rmb_price,
            cost_currency="ZMW" if product.product_type == "local" else "RMB",
            stock_quantity=product.stock_quantity,
            supplier_available_quantity=product.available_quantity,
            track_inventory=product.product_type == "local",
            is_active=True,
            is_default=True,
        ))
    ProductVariant.objects.bulk_create(variants, batch_size=500)


def remove_default_variants(apps, schema_editor):
    ProductVariant = apps.get_model('core', 'ProductVariant')
    ProductVariant.objects.filter(is_default=True, color__isnull=True, size__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=90)),
                ('hex_value', models.CharField(blank=True, max_length=7)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('source_option_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('supplier_sku', models.CharField(blank=True, max_length=120)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_currency', models.CharField(choices=[('RMB', 'RMB'), ('ZMW', 'ZMW'), ('USD', 'USD')], default='RMB', max_length=3)),
                ('selling_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('supplier_available_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['product', 'color__position', 'size__sort_order', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=90, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product_variant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productimage',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/customer/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/originals/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='processing_status',
            field=models.CharField(choices=[('original', 'Original'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.productcolor'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.productcolor'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='core.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.productvariant'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.productvariant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product', 'requested_size', 'requested_color'), name='unique_legacy_cart_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('cart', 'variant'), name='unique_cart_structured_variant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='core.size'),
        ),
        migrations.RunPython(create_default_variants, remove_default_variants),
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_product_color_code'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_product_color_size'),
        ),
    ]
