# Generated by Django 6.0.6 on 2026-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_private_original_images'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('size__isnull', True)), fields=('product',), name='unique_default_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('size__isnull', True)), fields=('product', 'color'), name='unique_product_color_only_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('size__isnull', False)), fields=('product', 'size'), name='unique_product_size_only_variant'),
        ),
    ]
