# Generated by Django 6.0.6 on 2026-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_seed_more_local_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_on_homepage",
            field=models.BooleanField(default=True),
        ),
    ]
