# Generated by Django 6.0.6 on 2026-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_product_homepage_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page view"),
                    ("search", "Search"),
                    ("zero_search", "Search with no results"),
                    ("product_view", "Product view"),
                    ("whatsapp_click", "WhatsApp click"),
                    ("add_to_cart", "Add to cart"),
                    ("completed_order", "Completed order"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
