# Generated by Django 6.0.6 on 2026-09-11 09:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_page_view_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='wholesale_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Discount off the retail price applied per unit once the wholesale quantity is reached.', max_digits=5),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='wholesale_min_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Minimum quantity of a single product needed to qualify for wholesale pricing.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_tier',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=12),
        ),
    ]
