# Generated by Django 6.0.6 on 2026-09-12 05:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_exchangerate_wholesale_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='parcel_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Flat fee (ZMW) charged to send a parcel through the biker network.', max_digits=12),
        ),
        migrations.CreateModel(
            name='ParcelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('dropoff_address', models.TextField()),
                ('parcel_description', models.CharField(max_length=255)),
                ('customer_note', models.TextField(blank=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests', to=settings.AUTH_USER_MODEL)),
                ('pickup_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_pickups', to='core.collectioncentre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('biker_fee_percentage_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biker_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('biker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_jobs', to='core.biker')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_jobs', to='core.collectioncentre')),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='core.parcelrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
