# Generated by Django 6.0.6 on 2026-09-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_exchangerate_parcel_delivery_fee_parcelrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='parcel_delivery_fee',
        ),
        migrations.AddField(
            model_name='parcelrequest',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recorded by staff when the parcel is collected and weighed.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set by staff after visiting to weigh the parcel and confirm the delivery distance. Blank until quoted.', max_digits=12, null=True),
        ),
    ]
