# Generated by Django 6.0.6 on 2026-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_exchangerate_parcel_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceljob',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='parcelrequest',
            name='pickup_centre',
        ),
        migrations.AddField(
            model_name='parcelrequest',
            name='pickup_address',
            field=models.TextField(default='', help_text='Where our team should come to collect the parcel from.'),
            preserve_default=False,
        ),
    ]
