# Generated by Django 6.0.6 on 2026-09-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_orderitem_referrer_referralreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Search history',
                'verbose_name_plural': 'Search history',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.marketplaceevent',),
        ),
    ]
