# Generated by Django 6.0.6 on 2026-09-04 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='ChinaZed Loans', max_length=120)),
                ('total_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_1_week', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('interest_2_weeks', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('interest_3_weeks', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('interest_4_weeks', models.DecimalField(decimal_places=2, default=45, max_digits=5)),
                ('remind_3_days_before', models.BooleanField(default=True)),
                ('remind_1_day_before', models.BooleanField(default=True)),
                ('remind_on_due_date', models.BooleanField(default=True)),
                ('remind_when_overdue', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('reminder_signature', models.CharField(blank=True, default='ChinaZed Loans', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan settings',
                'verbose_name_plural': 'Loan settings',
            },
        ),
        migrations.CreateModel(
            name='LoanCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('nrc_number', models.CharField(max_length=30, unique=True, verbose_name='NRC number')),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('employee_number', models.CharField(blank=True, max_length=60)),
                ('salary_date', models.CharField(blank=True, help_text="e.g. 28th, or 'last working day'", max_length=40)),
                ('next_of_kin', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='loans/customers/')),
                ('status', models.CharField(choices=[('good', 'Good customer'), ('late', 'Late'), ('blacklisted', 'Blacklisted')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('original_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Original principal plus every top-up.', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Flat interest for the whole period, %.', max_digits=5)),
                ('period_weeks', models.PositiveSmallIntegerField(choices=[(1, '1 Week'), (2, '2 Weeks'), (3, '3 Weeks'), (4, '4 Weeks')], default=4)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('bank', 'Bank transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('due_soon', 'Due soon'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='active', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=120)),
                ('receipt_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.loancustomer')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('bank', 'Bank transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('officer', models.CharField(blank=True, max_length=120)),
                ('paid_late', models.BooleanField(default=False)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('principal_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_topups_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='loans.loan')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('3_days_before', '3 days before due'), ('1_day_before', '1 day before due'), ('on_due', 'On due date'), ('overdue', 'After overdue')], max_length=20)),
                ('channel', models.CharField(default='log', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.loancustomer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.loan')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'kind'), name='loans_one_reminder_per_kind')],
            },
        ),
    ]
