# Generated by Django 6.0.6 on 2026-09-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancustomer',
            name='nrc_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NRC number'),
        ),
        migrations.AlterField(
            model_name='loancustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
