# Generated by Django 6.0.6 on 2026-09-04 14:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loancustomer_nrc_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual (staff)'), ('app', 'App (self-service)')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='loancustomer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked site account, for customers who apply in-app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_interest_1_week',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_interest_2_weeks',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_interest_3_weeks',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_interest_4_weeks',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_loan_growth_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text="Next limit = last repaid loan's amount x this, once they pay it off.", max_digits=4),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_loan_max_limit',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_loan_min_amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_loan_starting_limit',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Maximum a first-time borrower can request.', max_digits=10),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='app_loans_enabled',
            field=models.BooleanField(default=True, help_text='Turn the in-app Quick Loan feature on or off.'),
        ),
        migrations.CreateModel(
            name='LoanPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('bank', 'Bank transfer'), ('other', 'Other')], default='mobile_money', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved · received'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('decision_notes', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payment_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='loans.loan')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_request', to='loans.loanpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_weeks', models.PositiveSmallIntegerField(choices=[(1, '1 Week'), (2, '2 Weeks'), (3, '3 Weeks'), (4, '4 Weeks')])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payout_number', models.CharField(help_text='Mobile money number to deposit to (from their profile).', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved · deposited'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('decision_notes', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='loans.loancustomer')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_request', to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
