# Generated by Django 6.0.6 on 2026-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_source_loancustomer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansettings',
            name='auto_blacklist_enabled',
            field=models.BooleanField(default=True, help_text='Automatically blacklist a customer once a loan is this overdue.'),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='auto_blacklist_overdue_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Days past due before a customer is auto-blacklisted.'),
        ),
    ]
